/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_api_predictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateBuildingInput */
        CreateBuildingInput: {
            /**
             * Borough
             * @enum {string}
             */
            borough: "manhattan" | "brooklyn" | "queens" | "bronx" | "staten-island";
            /** Grossfloorareasqft */
            grossFloorAreaSqft: number;
            /** Numberofbuildings */
            numberOfBuildings: number;
            /**
             * Propertytype
             * @enum {string}
             */
            propertyType: "multifamily-housing" | "office" | "hotel" | "retail" | "hospital" | "mixed-use";
            /** Yearbuilt */
            yearBuilt: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LL97 */
        LL97: {
            /** Atrisk */
            atRisk: boolean;
            /** Capkbtupersqft2024To2029 */
            capKbtuPerSqft2024To2029: number;
            /** Capkbtupersqft2030To2034 */
            capKbtuPerSqft2030To2034: number;
            /** Projectedannualfineusd2024 */
            projectedAnnualFineUsd2024: number;
            /** Projectedannualfineusd2030 */
            projectedAnnualFineUsd2030: number;
        };
        /** Peer */
        Peer: {
            cohort: components["schemas"]["PeerCohort"];
            /** Cohortsize */
            cohortSize: number;
            /** Mediansiteeui */
            medianSiteEui: number;
            /** P25Siteeui */
            p25SiteEui: number;
            /** P75Siteeui */
            p75SiteEui: number;
            /** Percentile */
            percentile: number;
        };
        /** PeerCohort */
        PeerCohort: {
            /**
             * Ageband
             * @enum {string}
             */
            ageBand: "pre-1950" | "1950-1979" | "1980-1999" | "2000-plus";
            /**
             * Borough
             * @enum {string}
             */
            borough: "manhattan" | "brooklyn" | "queens" | "bronx" | "staten-island";
            /**
             * Propertytype
             * @enum {string}
             */
            propertyType: "multifamily-housing" | "office" | "hotel" | "retail" | "hospital" | "mixed-use";
        };
        /** Prediction */
        Prediction: {
            /** Intervalhigh */
            intervalHigh: number;
            /** Intervallow */
            intervalLow: number;
            /** Modelversion */
            modelVersion: string;
            /** Siteeuikbtupersqft */
            siteEuiKbtuPerSqft: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Id */
            id: string;
            input: components["schemas"]["CreateBuildingInput"];
            ll97: components["schemas"]["LL97"];
            peer: components["schemas"]["Peer"];
            prediction: components["schemas"]["Prediction"];
        };
        /** PredictionResponseEnvelope */
        PredictionResponseEnvelope: {
            data: components["schemas"]["PredictionResponse"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_api_predictions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBuildingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
